audit_header: false
title: "New Haven & Fairfield County's Best Real Estate Training"
description: Jonathan Carbutti, a top Real Estate Agent in New Haven & Fairfield County, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Agent Success Stories
    url: /agent-success-stories/

client:
  name: Jonathan Carbutti
  title:
  license_number:
  about_markdown: |
    Jonathan defines himself as an educator first, and real estate broker second. He enjoys educating the consumer, Buyers and Sellers alike, and dispelling many of the “myths” of buying and selling. As a successful real estate investor as well Jonathan is able to offer practical and useful advice whether you are the first-time investor or seasoned pro.
  market: New Haven & Fairfield County
  brand: Carbutti & Co Realtors
  brokerage:
  address: 72 South Main Street Wallingford, CT 06492
  phone: 203-980-6886
  phone_type:
  phone2:
  phone2_type:
  email: jonathn.carbutti@gmail.com
  url: http://www.jonathancarbutti.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Carbutti & Co Realtors can take your business to new heights."
    CTA_link_text: "Send a Private Email"
    CTA_url: mailto:jonathan.carbutti@gmail.com

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/carbuttirealtors
  linkedin_url: https://www.linkedin.com/in/jonathancarbutti
  youtube_url: https://www.youtube.com/channel/UCiKVxtj6Si3d6fCxp1Vag2w
  twitter_url: https://twitter.com/CarbuttiBlog
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'New Haven & Fairfield County Real Estate Podcast with Jonathan Carbutti'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the New Haven & Fairfield County Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Carbutti & Co Realtors - your professional New Haven & Fairfield County Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in New Haven & Fairfield County, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jonathan Carbutti'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: New Haven & Fairfield County Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#002F59'
  accent_color: '#0070ac'
  theme_color: '#323232'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#002F59'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
